### ISSUE TITLE
Network error not shown for compile failure

### ISSUE THREAD

**Issue by vbar** [XRPLF/xrpl-hooks-ide#135]
e.g. when the compilation backend isn't available at all:
![network](https://user-images.githubusercontent.com/108574/158326083-94ef94aa-a74e-4180-b04e-28993c3fb461.png)

Development log should show a specific error in this case, so that user knows changing the hook source is unlikely to help.

**Comment by muzam1l** [comment]
Error messages in #256 are now distinct for possible network error, compilation error, invalid binary error, etc!
