### ISSUE TITLE
Error codes in debug stream should be linked to documentation

### ISSUE THREAD

**Issue by vbar** [XRPLF/xrpl-hooks-ide#170]
As @RichardAH put it (lightly edited):
Log codes are the numbers that presently appear after some HookSet trace lines, e.g. HookSet(1)[...
Each message type has a unique code so the IDE can link it to some documentation page, to help the user understand what they are doing wrong.

This is related to #139 (it isn't a duplicate mainly because it concerns a different log).

**Comment by dangell7** [comment]
https://xrpl.org/tec-codes.html
https://xrpl.org/ter-codes.html
https://xrpl.org/tel-codes.html
https://xrpl.org/tef-codes.html

And then in hooks there are their own error codes.

https://xrpl-hooks.readme.io/reference/negative-return-codes
