### ISSUE TITLE
IDE restart on more complicated debugging

### ISSUE THREAD

**Issue by vbar** [XRPLF/xrpl-hooks-ide#180]
IDE can reset (not quite reproducibly, but repeatedly) on deployments combined with active debug stream. For example, when testing the carbon example:

- in carbon.c, change hardcoded beneficiary (rfCarbonVNTuXckX6x2qTMFmFSnm6dEWGX) to your Carol's account
- compile carbon.c & deploy to Alice account
- in test tab, set up payment from Alice to Bob
- open debug stream filtered on Carol
- run test & see incoming payment
- back in develop tab, add the recommended tracing of the call to util_accid
- compile carbon.c & deploy to Alice account
- switch to test tab again
- see the IDE restart and loose both develop and test changes

console has some error which doesn't make a lot of sense to me:
![restart](https://user-images.githubusercontent.com/108574/165757966-af8c2595-60fe-4f03-a9cd-770a5be6b860.png)

**Comment by muzam1l** [comment]
Tried reproducing but couldn't. Error message also indicates network error at that time could have been an issue. Need concise steps to reproduce.

**Comment by vbar** [comment]
Hmm, I can't reproduce it either - I don't think it was a network error, but maybe some other change fixed it...
