### ISSUE TITLE
Account removal should reset test transaction

### ISSUE THREAD

**Issue by vbar** [XRPLF/xrpl-hooks-ide#206]
![test](https://user-images.githubusercontent.com/108574/171819342-e9ab2e82-0e46-4fbe-bf1b-d5baf3bc6b75.png)

The test transaction above looks valid but isn't: Alice account was replaced after selecting the field. Builder shouldn't get into a state where "Alice" means different accounts on the same page (some of which it can no longer find), and the easiest way to prevent it is probably by resetting the test transaction whenever an account is deleted.

**Comment by muzam1l** [comment]
Resetting transaction would be too harsh, better way would be to somehow update the account field, either reset account field or remove its "old" name?

**Comment by vbar** [comment]
> Resetting transaction would be too harsh, better way would be to somehow update the account field, either reset account field or remove its "old" name?

well, yes, I suppose you know what the account fields are and can reset them without touching the rest of transaction...
