### ISSUE TITLE
Cannot add file and import my own macros

### ISSUE THREAD

**Issue by dangell7** [XRPLF/xrpl-hooks-ide#230]
Context:

I wanted to add my own macro file to import instead of adding the macro's to the top of the file.

_It says, "Cannot edit in read only editor"

Then I logged in, with the already added header file. 

At this point I tried to create a new gist. It failed. I deleted the header file, then I could create a new gist.

Then I re-added the new header file, still read only bug. Then I tried to sync with my gist and it failed._

Otherwise its pure perfection. :)

**Comment by vbar** [comment]
Yes, headers are read-only, because integrating changes from multiple sources is tricky in Hooks Builder: it uses remote Language Server, and the distributed [LSP](https://microsoft.github.io/language-server-protocol/) doesn't really support multiple files... But we take patches... :-)
