### ISSUE TITLE
Minor Bugs: Cannot abort discard. Json Tx changes between json/txbuilder

### ISSUE THREAD

**Issue by dangell7** [XRPLF/xrpl-hooks-ide#252]
A few bugs on the builder.

1. Save/Draft - Cannot abort discard draft.

Steps to reproduce;
- Navigate to "Test" Tab
- NFTokenOfferCreate
- Enter Json Mode
- Add "Destination"
- "discard" Draft

There is no option to quit. I think you wanted a "Cancel" there to back out?

2. "Json/Tx Builder" changes transaction between enter/exit json
2.1: Changes on Submit
2.2: Cannot Save

I'm not sure if you're coding in default transaction fields from the library or you have some default settings in the ide, but when creating the Sell side of the NFTokenOfferCreate I want to add the destination. When I change from json/builder it removes the "Destination"

- Navigate to "Test" Tab
- NFTokenOfferCreate
- Enter Json Mode
- Add "Destination" - * I love the autofill
- Exit Json

It removes the Destination. It also removes the destination on submit (sometimes, had trouble reproducing on successful txs.) and I cannot save.

**Comment by muzam1l** [comment]
> There is no option to quit. I think you wanted a "Cancel" there to back out?

Currently you can quit by pressing `Escape`, but yeah it would be good to have cancel button there.

> 2.1: Changes on Submit

So in json mode, fields may seem rearranged on submit, but is essentially the same data. Will see if this behavior can be removed entirely!

> 2.2: Cannot Save

That may happen if tx data is not changed, like by adding spaces, will try to improve UX there too!

> When I change from json/builder it removes the "Destination"

Well that's a bug, default fields are taken from `content/transactions.json`. About `Destination`, if the transaction does not have `Destination` in those fields, it is removed on save. Will fix it soon!

**Comment by dangell7** [comment]
https://github.com/XRPLF/xrpl-hooks-ide/pull/253
